[package]
name = "hostess"
description = "Fast, Pomf-compatible file server written with Actix & SeaORM"
version = "0.1.1"
authors = ["Ashton L. <ashton@spysat.net>", "Josie E."]
homepage = "https://hostess.lol"
repository = "https://github.com/ashtonqlb/nakai"
license = "GPL-3.0"
edition = "2021"
publish = false

[workspace]
members = ["api", "service", "migration"]

[workspace.dependencies]
rusqlite = { version = "0.32.1", features = ["bundled"] }


[dependencies]
hostess-api = { path = "api" }
actix-web = "4.9.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
actix-files = "0.6.6"
dotenvy = "0.15"
listenfd = "1"